
services:
  app:
    image: devcontainer-app:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
       - USERNAME=$USERNAME
       - USER_UID=$USER_UID
       - USER_GID=$USER_GID
    environment:
      - APP_HOST=$APP_HOST
      - APP_PORT=$APP_PORT
      - APP_DEBUG=$APP_DEBUG
    ports:
      - $APP_PORT:$APP_PORT
