services:
  app:
    image: devcontainer-app:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
       - USERNAME=vscode
       - USER_UID=1000
       - USER_GID=1000
    environment:
      - APP_HOST=$APP_HOST
      - APP_PORT=$APP_PORT
      - APP_DEBUG=$APP_DEBUG
    ports:
      - $APP_PORT:$APP_PORT

  worker:
    image: devcontainer-app:latest
    command: celery --app=worker worker --loglevel=info
    depends_on:
      - app

  rabbitmq:
    image: rabbitmq
